# -*- mode: ruby -*-
# vi: set ft=ruby :
# need to install node via NVM and npm at 0.10 and ~2.3

Vagrant.configure(2) do |config|
  config.vm.box = "parallels/ubuntu-14.04"
  config.vm.network "private_network", ip: "192.168.1.10"
  config.vm.synced_folder "/Users/ian/Workspaces/Fnet", "/opt/Workspaces"
  config.vm.provider "parallels" do |prl|
  	prl.name = "node_js"
	prl.memory = 4096
	prl.cpus = 2
  end
  config.vm.provision "shell", inline: <<-SHELL
    	sudo apt-get update
	sudo apt-get install -y build-essential
	sudo apt-get install -y postgresql postgresql-contrib libpq-dev
	sudo apt-get install -y vim git
  SHELL
end
